[package]
name = "hyper-example"
version = "0.1.0"
edition = "2021"

[dependencies]
octoapp = { path = "../../..", features = ["hyper"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
dotenvy = "0.15"
